### ISSUE TITLE
Problem training specific model

### ISSUE THREAD

**Issue by Lycoris52** [Plachtaa/VITS-fast-fine-tuning#295]
@Plachtaa , 
Thank you for sharing a brilliant repository, I have some questions.

After many test with your huggingface spaces below
https://huggingface.co/spaces/Plachta/VITS-Umamusume-voice-synthesizer

I found that the japanese intonation on the japanese only version (the one with only Umamusume) is better than the trilingual one.
Could you give me more detailed information about the base model you use for the Japanese only version, or any specific details for fine-tuning them.
I tried using the same config with the G_jp model on above Huggingface space repository but an error occurred

```
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([40, 192]) from checkpoint, the shape in current model is torch.Size([68, 192]).
```

Any advice is appreciate.
Thank you in advance

**Comment by Plachtaa** [comment]
`size mismatch` is because the trilingual model use a different phoneme vocabulary (with 68 phonemes) from the pure Japanese one (with 40 phonemes).
If you intend to use the Japanese model, you should cony its corresponding config file (`config.json`) as well, which states the g2p tool used and its phoneme vocabulary.

**Comment by Lycoris52** [comment]
@Plachtaa 
Thank you for your advice. I have been able to finetune model mention above with good result!
